linters:
  enable:
    - dupl
    - errname
    - errorlint
    - errcheck
    - forcetypeassert
    - ginkgolinter
    - goconst
    - gocritic
    - godot
    - gosimple
    - gofumpt
    - gosec
    - govet
    - goimports
    - ineffassign
    - misspell
    - nilerr
    - prealloc
    - promlinter
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
    - gocognit

linters-settings:
  errcheck:
    check-type-assertions: true
  gofumpt:
    extra-rules: true
  govet:
    enable-all: true
  gocognit:
    min-complexity: 15
  revive:
    ignore-generated-header: true
    enable-all-rules: true
    rules:
      - name: line-length-limit
        arguments: [120]
      - name: file-header
        disabled: true

run:
  timeout: 2m
