language: go
go:
  - 1.23.4
services:
  - docker

before_install:
  - export GO111MODULE=on
  - export GOPRIVATE=github.ibm.com
  - git config --global url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.ibm.com".insteadOf "https://github.ibm.com"

jobs:
  include:
    - stage: "Basic Checks"
      before_script:
        - go install golang.org/x/tools/cmd/goimports@latest
        - go install honnef.co/go/tools/cmd/staticcheck@latest
        - go install mvdan.cc/gofumpt@latest
        - go install github.com/golang/protobuf/protoc-gen-go@latest
      script:
        - set -e
        - make linter
        - make check-deps
        - bash ./scripts/check_protos.sh
    - stage: "Tests"
      name: "Unit Tests"
      script: 
        - set -e
        - go test -race ./...
    - stage: "Tests"
      name: "Armageddon Test"
      script:
        - set -e
        - (cd node/examples; bash ./scripts/build_docker.sh)
        - (bash ./node/examples/scripts/run_sample.sh)
