language: go
go:
  - 1.21.0
before_script:
- go install golang.org/x/tools/cmd/goimports@latest
- go install honnef.co/go/tools/cmd/staticcheck@latest
- go install mvdan.cc/gofumpt@latest
script:
- set -e
- make linter
- make check-deps
- go test -race ./...
- (cd node; PATH=$PATH:orderingservice-experiments/clients/cmd/client/ go test -race ./... )
