language: go
go:
  - 1.23.4
services:
  - docker

jobs:
  include:
    - stage: "Basic Checks"
      before_script:
        - go install golang.org/x/tools/cmd/goimports@latest
        - go install honnef.co/go/tools/cmd/staticcheck@latest
        - go install mvdan.cc/gofumpt@latest
        - go install github.com/golang/protobuf/protoc-gen-go@latest
        - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
      script:
        - set -e
        - make linter
        - make check-deps
        - bash ./scripts/check_protos.sh
    - stage: "Tests"
      name: "Unit Tests"
      script: 
        - set -e
        - go test -race ./...
    - stage: "Tests"
      name: "Armageddon Test"
      script:
        - set -e
        - (cd node/examples; bash ./scripts/build_docker.sh)
        - (bash ./node/examples/scripts/run_sample.sh)
