PartyID: 3
General:
    ListenAddress: 127.0.0.1
    ListenPort: 56885
    TLS:
        Enabled: true
        PrivateKey: /var/folders/5c/y9fv760d0zv82b77lvwlqp4h0000gn/T/TestLocalConfigGeneration1922188677/crypto/ordererOrganizations/org3/orderers/party3/consenter/key.pem
        Certificate: /var/folders/5c/y9fv760d0zv82b77lvwlqp4h0000gn/T/TestLocalConfigGeneration1922188677/crypto/ordererOrganizations/org3/orderers/party3/consenter/tls-cert.pem
        RootCAs:
            - /var/folders/5c/y9fv760d0zv82b77lvwlqp4h0000gn/T/TestLocalConfigGeneration1922188677/crypto/ordererOrganizations/Org3/tlsca/cacert.pem
    Keepalive:
        ClientInterval: 1m0s
        ClientTimeout: 20s
        ServerInterval: 2h0m0s
        ServerTimeout: 20s
        ServerMinInterval: 1m0s
    Backoff:
        BaseDelay: 1s
        Multiplier: 1.6
        MaxDelay: 2m0s
    MaxRecvMsgSize: 104857600
    MaxSendMsgSize: 104857600
    Bootstrap:
        Method: yaml
        File: /var/dec-trust/production/orderer/bootstrap/bootstrap.yaml
    Cluster:
        SendBufferSize: 2000
        ClientCertificate: /var/folders/5c/y9fv760d0zv82b77lvwlqp4h0000gn/T/TestLocalConfigGeneration1922188677/crypto/ordererOrganizations/org3/orderers/party3/consenter/tls-cert.pem
        ClientPrivateKey: /var/folders/5c/y9fv760d0zv82b77lvwlqp4h0000gn/T/TestLocalConfigGeneration1922188677/crypto/ordererOrganizations/org3/orderers/party3/consenter/key.pem
    LocalMSPDir: /var/dec-trust/production/orderer/crypto
    LocalMSPID: OrdererOrg
    LogSpec: info
FileStore:
    Location: /var/dec-trust/production/orderer/store
Consensus:
    WALDir: /var/dec-trust/production/orderer/store/smartbft/wal
