################################################################################
#
#    Arma Batcher Configuration Template
#
################################################################################

# PartyID a unique identifier for each Arma party, uint16, id>0
PartyID: 1

################################################################################
#
#   SECTION: General: same as in template
#
################################################################################
General:

################################################################################
#
#   SECTION: File Store: same as in template
#
################################################################################
FileStore:

################################################################################
#
#   SECTION: Role specific configuration: only `Batcher` key
#
################################################################################

# Batcher specific parameters
Batcher:
  # ShardID a unique identifier for each Arma shard; uint16, MaxUint16> id >0.
  ShardID: 1
  