################################################################################
#
#    Arma Consenter Configuration Template
#
################################################################################

# PartyID a unique identifier for each Arma party, uint16, id>0
PartyID: 1

################################################################################
#
#   SECTION: General: same as in template
#
################################################################################
General:

################################################################################
#
#   SECTION: File Store: same as in template
#
################################################################################
FileStore:

################################################################################
#
#   SECTION: Role specific configuration: only `Consensus` key
#
################################################################################

# Consensus specific parameters
Consensus:
  # WALDir specifies the location at which Write Ahead Logs for SmartBFT are
  # stored. Each channel will have its own subdir named after channel ID.
  WALDir: /var/dec-trust/production/orderer/smartbft/wal
