PartyID: 4
General:
    ListenAddress: 127.0.0.1
    ListenPort: 52816
    TLS:
        Enabled: true
        PrivateKey: /var/dec-trust/crypto/ordererOrganizations/org4/orderers/party4/batcher2/key.pem
        Certificate: /var/dec-trust/crypto/ordererOrganizations/org4/orderers/party4/batcher2/tls-cert.pem
        RootCAs:
            - /var/dec-trust/crypto/ordererOrganizations/org4/orderers/party4/tlsca/cacert.pem
    Keepalive:
        ClientInterval: 1m0s
        ClientTimeout: 20s
        ServerInterval: 2h0m0s
        ServerTimeout: 20s
        ServerMinInterval: 1m0s
    Backoff:
        BaseDelay: 1s
        Multiplier: 1.6
        MaxDelay: 2m0s
    MaxRecvMsgSize: 104857600
    MaxSendMsgSize: 104857600
    Bootstrap:
        Method: yaml
        File: /var/dec-trust/bootstrap/shared_config.yaml)
    LocalMSPDir: /var/dec-trust/crypto/ordererOrganizations/org4/orderers/party4/batcher2
    LocalMSPID: OrdererOrg
    LogSpec: info
FileStore:
    Location: /var/dec-trust/store
Batcher:
    ShardID: 2
