PartyID: 2
General:
    ListenAddress: 127.0.0.1
    ListenPort: 52802
    TLS:
        Enabled: false
        PrivateKey: /var/dec-trust/crypto/ordererOrganizations/org2/orderers/party2/assembler/key.pem
        Certificate: /var/dec-trust/crypto/ordererOrganizations/org2/orderers/party2/assembler/tls-cert.pem
        RootCAs:
            - /var/dec-trust/crypto/ordererOrganizations/org2/orderers/party2/tlsca/cacert.pem
        ClientAuthRequired: false
    Keepalive:
        ClientInterval: 1m0s
        ClientTimeout: 20s
        ServerInterval: 2h0m0s
        ServerTimeout: 20s
        ServerMinInterval: 1m0s
    Backoff:
        BaseDelay: 1s
        Multiplier: 1.6
        MaxDelay: 2m0s
    MaxRecvMsgSize: 104857600
    MaxSendMsgSize: 104857600
    Bootstrap:
        Method: yaml
        File: /var/dec-trust/bootstrap/shared_config.yaml)
    LocalMSPDir: /var/dec-trust/crypto/ordererOrganizations/org2/orderers/party2/assembler/msp
    LocalMSPID: OrdererOrg
    LogSpec: info
FileStore:
    Location: /var/dec-trust/store
Assembler:
    PrefetchBufferMemoryBytes: 1073741824
    LedgerScanTimeout: 5s
    EvictionTtl: 1h
    ReplicationChannelSize: 100
    BatchRequestsChannelSize: 1000