PartyID: 1
General:
    ListenAddress: 127.0.0.1
    ListenPort: 52798
    TLS:
        Enabled: true
        PrivateKey: /var/dec-trust/crypto/ordererOrganizations/org1/orderers/party1/consenter/key.pem
        Certificate: /var/dec-trust/crypto/ordererOrganizations/org1/orderers/party1/consenter/tls-cert.pem
        RootCAs:
            - /var/dec-trust/crypto/ordererOrganizations/org1/orderers/party1/tlsca/cacert.pem
    Keepalive:
        ClientInterval: 1m0s
        ClientTimeout: 20s
        ServerInterval: 2h0m0s
        ServerTimeout: 20s
        ServerMinInterval: 1m0s
    Backoff:
        BaseDelay: 1s
        Multiplier: 1.6
        MaxDelay: 2m0s
    MaxRecvMsgSize: 104857600
    MaxSendMsgSize: 104857600
    Bootstrap:
        Method: yaml
        File: /var/dec-trust/bootstrap/shared_config.yaml)
    Cluster:
        SendBufferSize: 2000
        ClientCertificate: /var/dec-trust/crypto/ordererOrganizations/org1/orderers/party1/consenter/tls-cert.pem
        ClientPrivateKey: /var/dec-trust/crypto/ordererOrganizations/org1/orderers/party1/consenter/key.pem
    LocalMSPDir: /var/dec-trust/crypto/ordererOrganizations/org1/orderers/party1/consenter
    LocalMSPID: OrdererOrg
    LogSpec: info
FileStore:
    Location: /var/dec-trust/store
Consensus:
    WALDir: /var/dec-trust/store/smartbft/wal
