# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: Release Fabric-X Orderer Docker Image

on:
  push:
    tags:
      - "v*" # Triggers on tags like v0.0.14

permissions:
  contents: read
  packages: write

jobs:
  docker-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up QEMU (for cross-platform builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Extract version from tag
        id: extract
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      
      - name: Print GitHub Repository Owner
        run: echo "Repository owner is ${{ github.repository_owner }}"

      - name: Set image prefix
        run: |
          if [ "${{ github.repository_owner }}" = "hyperledger" ]; then
            echo "IMAGE_PREFIX=hyperledger" >> $GITHUB_ENV
           else
            echo "IMAGE_PREFIX=${{ secrets.DOCKER_HUB_USERNAME }}" >> $GITHUB_ENV
          fi

      - name: Build and Push Multi-Platform Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./images/multi-platform/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/s390x
          push: true
          tags: |
            docker.io/${{ env.IMAGE_PREFIX }}/fabric-x-orderer:latest
            docker.io/${{ env.IMAGE_PREFIX }}/fabric-x-orderer:${{ env.VERSION }}
