# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

x-base: &base
  image: "arma"

x-stage: &stage
  image: "alpine"
  command: sh -c "echo stage completed"

x-consenter: &consenter
  <<: *base

x-batcher: &batcher
  <<: *base
  depends_on:
    consenter_stage:
      condition: service_completed_successfully

x-assembler: &assembler
  <<: *base
  depends_on:
    batcher_stage:
      condition: service_completed_successfully

x-router: &router
  <<: *base
  depends_on:
    assembler_stage:
      condition: service_completed_successfully

services:

  ## consenters ....

  consenter.p1:
    <<: *consenter
    command: consensus --config=tmp/arma-sample/config/party1/local_config_consenter.yaml
    hostname: consensus.p1
    volumes:
      - /tmp/arma-sample:/tmp/arma-sample

  consenter.p2:
    <<: *consenter
    command: consensus --config=tmp/arma-sample/config/party2/local_config_consenter.yaml
    hostname: consensus.p2
    volumes:
      - /tmp/arma-sample:/tmp/arma-sample

  consenter.p3:
    <<: *consenter
    command: consensus --config=tmp/arma-sample/config/party3/local_config_consenter.yaml
    hostname: consensus.p3
    volumes:
      - /tmp/arma-sample:/tmp/arma-sample

  consenter.p4:
    <<: *consenter
    command: consensus --config=tmp/arma-sample/config/party4/local_config_consenter.yaml
    hostname: consensus.p4
    volumes:
      - /tmp/arma-sample:/tmp/arma-sample

  consenter_stage:
    <<: *stage
    depends_on:
      - consenter.p1
      - consenter.p2
      - consenter.p3
      - consenter.p4

  ## batchers ....

  batcher1.p1:
    <<: *batcher
    command: batcher --config=tmp/arma-sample/config/party1/local_config_batcher1.yaml
    hostname: batcher1.p1
    volumes:
      - /tmp/arma-sample:/tmp/arma-sample

  batcher2.p1:
    <<: *batcher
    command: batcher --config=tmp/arma-sample/config/party1/local_config_batcher2.yaml
    hostname: batcher2.p1
    volumes:
      - /tmp/arma-sample:/tmp/arma-sample

  batcher1.p2:
    <<: *batcher
    command: batcher --config=tmp/arma-sample/config/party2/local_config_batcher1.yaml
    hostname: batcher1.p2
    volumes:
      - /tmp/arma-sample:/tmp/arma-sample

  batcher2.p2:
    <<: *batcher
    command: batcher --config=tmp/arma-sample/config/party2/local_config_batcher2.yaml
    hostname: batcher2.p2
    volumes:
      - /tmp/arma-sample:/tmp/arma-sample

  batcher1.p3:
    <<: *batcher
    command: batcher --config=tmp/arma-sample/config/party3/local_config_batcher1.yaml
    hostname: batcher1.p3
    volumes:
      - /tmp/arma-sample:/tmp/arma-sample

  batcher2.p3:
    <<: *batcher
    command: batcher --config=tmp/arma-sample/config/party3/local_config_batcher2.yaml
    hostname: batcher2.p3
    volumes:
      - /tmp/arma-sample:/tmp/arma-sample

  batcher1.p4:
    <<: *batcher
    command: batcher --config=tmp/arma-sample/config/party4/local_config_batcher1.yaml
    hostname: batcher1.p4
    volumes:
      - /tmp/arma-sample:/tmp/arma-sample

  batcher2.p4:
    <<: *batcher
    command: batcher --config=tmp/arma-sample/config/party4/local_config_batcher2.yaml
    hostname: batcher2.p4
    volumes:
      - /tmp/arma-sample:/tmp/arma-sample

  batcher_stage:
    <<: *stage
    depends_on:
      - batcher1.p1
      - batcher2.p1
      - batcher1.p2
      - batcher2.p2
      - batcher1.p3
      - batcher2.p3
      - batcher1.p4
      - batcher2.p4

  ## assemblers ....

  assembler.p1:
    <<: *assembler
    command: assembler --config=tmp/arma-sample/config/party1/local_config_assembler.yaml
    volumes:
      - /tmp/arma-sample:/tmp/arma-sample

  assembler.p2:
    <<: *assembler
    command: assembler --config=tmp/arma-sample/config/party2/local_config_assembler.yaml
    volumes:
      - /tmp/arma-sample:/tmp/arma-sample

  assembler.p3:
    <<: *assembler
    command: assembler --config=tmp/arma-sample/config/party3/local_config_assembler.yaml
    volumes:
      - /tmp/arma-sample:/tmp/arma-sample

  assembler.p4:
    <<: *assembler
    command: assembler --config=tmp/arma-sample/config/party4/local_config_assembler.yaml
    volumes:
      - /tmp/arma-sample:/tmp/arma-sample

  assembler_stage:
    <<: *stage
    depends_on:
      - assembler.p1
      - assembler.p2
      - assembler.p3
      - assembler.p4

  ## routers ....

  router.p1:
    <<: *router
    command: router --config=tmp/arma-sample/config/party1/local_config_router.yaml
    volumes:
      - /tmp/arma-sample:/tmp/arma-sample

  router.p2:
    <<: *router
    command: router --config=tmp/arma-sample/config/party2/local_config_router.yaml
    volumes:
      - /tmp/arma-sample:/tmp/arma-sample

  router.p3:
    <<: *router
    command: router --config=tmp/arma-sample/config/party3/local_config_router.yaml
    volumes:
      - /tmp/arma-sample:/tmp/arma-sample

  router.p4:
    <<: *router
    command: router --config=tmp/arma-sample/config/party4/local_config_router.yaml
    volumes:
      - /tmp/arma-sample:/tmp/arma-sample
